### ISSUE TITLE
"You you need to decide where to send your adventurers  "

### ISSUE THREAD

**Issue by AndyHunt66** [AntonioSoler/bga-takaraisland#2]
When it's your go, the banner at the top of the screen (just after the rotating sand-timer) says:
"You you need to decide where to send your adventurers  "

It should just say:
"You need to decide where to send your adventurers  "

**Comment by AndyHunt66** [comment]
I'm changing it as part of the read-through

**Comment by AntonioSoler** [comment]
fixed
