### ISSUE TITLE
Indicate which site the current spread of cards is from

### ISSUE THREAD

**Issue by AndyHunt66** [AntonioSoler/bga-takaraisland#7]
When the cards are spread out, there should be a marker on the main board to show which site they are from.
Maybe something like a light shadow, or a border around the site? not sure.

There should also be something to tell you on the spread-out cards, which site they came from - maybe a tooltip fo face-down cards? Maybe a tool-tip on the 'spreading' animation? (a tooltip on a tooltip!!!!)

**Comment by AntonioSoler** [comment]
added a tooltip to the browse/gather button that indicates the deck number
